"""The demonstration display must show measurement, not truth.

A plan view is the easiest place in this project to cheat. Drawing A where the
simulator put it would look identical to drawing A where the camera measured
it, right up until someone asks which one it is. These tests pin the honest
answer, and they drive the display with real observer messages rather than
inspecting its constructor.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import rclpy
from scene.build import build_scene

# corridor_interfaces is generated by colcon, so it exists under `colcon test`
# but not in a bare repository pytest run. viz_node imports it at module level,
# so the skip has to come before that import. The source-only audits of this
# display live in test_observer_scaffold.py, where they run unconditionally.
messages = pytest.importorskip(
    "corridor_interfaces.msg", reason="colcon-generated interfaces; run via colcon test"
)

from police_observer.viz_node import EnforcementViewNode  # noqa: E402
from visualization_msgs.msg import Marker  # noqa: E402

SpeedEstimate = messages.SpeedEstimate
SpeedViolation = messages.SpeedViolation


@pytest.fixture(scope="module")
def manifest(tmp_path_factory: pytest.TempPathFactory) -> Path:
    output = tmp_path_factory.mktemp("enforcement_view") / "corridor.usda"
    _, manifest_path = build_scene(None, output, 6.0, 3.0)
    return manifest_path


@pytest.fixture()
def node(manifest: Path):
    # Pass the manifest the way a launch file does, through ROS arguments,
    # rather than reaching past the node's own parameter handling.
    rclpy.init(args=["--ros-args", "-p", f"manifest_path:={manifest}"])
    view = EnforcementViewNode()
    try:
        yield view
    finally:
        view.destroy_node()
        rclpy.shutdown()


def _estimate(station_m: float, speed_mps: float, limit_mps: float) -> SpeedEstimate:
    message = SpeedEstimate()
    message.corridor_profile = "nominal_m6_n3"
    message.station_m = station_m
    message.speed_mps = speed_mps
    message.speed_stddev_mps = 0.04
    message.corridor_width_m = 3.0
    message.speed_limit_mps = limit_mps
    message.valid = True
    return message


def _published(node: EnforcementViewNode) -> dict[str, list[Marker]]:
    """Capture one MarkerArray without needing an executor or a subscriber."""

    captured: list = []
    original = node.markers.publish
    node.markers.publish = captured.append  # type: ignore[method-assign]
    try:
        node._publish()
    finally:
        node.markers.publish = original  # type: ignore[method-assign]
    grouped: dict[str, list[Marker]] = {}
    for marker in captured[-1].markers:
        grouped.setdefault(marker.ns, []).append(marker)
    return grouped


def test_robot_is_drawn_at_the_measured_station_not_at_truth(node) -> None:
    """The dot must move because the camera said so.

    Two different measured stations must move the marker by the corresponding
    distance along the surveyed route. A display sourcing simulator truth would
    ignore these messages entirely and never move.
    """

    assert "robot" not in _published(node)  # nothing measured yet

    node._on_estimate(_estimate(station_m=4.0, speed_mps=1.0, limit_mps=1.2))
    near = _published(node)["robot"][0].pose.position

    node._on_estimate(_estimate(station_m=10.0, speed_mps=1.0, limit_mps=0.8))
    far = _published(node)["robot"][0].pose.position

    assert far.x > near.x
    assert far.x - near.x == pytest.approx(6.0, abs=0.15)


def test_a_station_off_the_approach_does_not_kill_the_display(node) -> None:
    """This runs in a subscription callback, so an exception ends the display.

    A SpeedMeasurement always carries a surveyed gate station today, so the
    lookup cannot fail -- but nothing enforces that, and one refactor that
    published a raw observation station would take RViz down mid-run rather
    than lose one marker.
    """

    node._on_estimate(_estimate(station_m=10.0, speed_mps=1.0, limit_mps=0.8))
    assert "robot" in _published(node)

    node._on_estimate(_estimate(station_m=40.0, speed_mps=1.0, limit_mps=0.8))
    namespaces = _published(node)
    assert "robot" not in namespaces, "the marker is dropped, not the display"
    # Everything else still renders, including the readout.
    assert {"corridor", "occluders", "route", "readout"} <= set(namespaces)


def test_readout_reports_speed_limit_width_and_profile(node) -> None:
    node._on_estimate(_estimate(station_m=10.0, speed_mps=1.02, limit_mps=0.8))
    text = _published(node)["readout"][0].text
    for expected in ("nominal_m6_n3", "10.00", "1.02", "0.80", "3.00"):
        assert expected in text, f"readout is missing {expected}: {text!r}"


def test_violation_turns_the_display_red_and_a_compliant_estimate_clears_it(node) -> None:
    node._on_estimate(_estimate(station_m=10.0, speed_mps=1.02, limit_mps=0.8))
    assert _published(node)["readout"][0].color.g > 0.5  # compliant green

    violation = SpeedViolation()
    violation.event_id = 1
    violation.exceedance_mps = 0.22
    node._on_violation(violation)
    readout = _published(node)["readout"][0]
    assert readout.color.r > 0.8 and readout.color.g < 0.5
    assert "VIOLATION #1" in readout.text
    assert _published(node)["robot"][0].color.r > 0.8

    node._on_estimate(_estimate(station_m=12.0, speed_mps=0.5, limit_mps=0.8))
    assert _published(node)["readout"][0].color.g > 0.5


def test_a_boundary_measurement_rearms_the_display_like_the_detector(node) -> None:
    """A6-M2: the display and the detector must rearm on the same measurement.

    RViz used to clear a displayed violation on raw speed <= limit, while
    ``ViolationDetector`` rearms on the conservative, confidence-discounted
    speed. A measurement between those two thresholds -- over the limit raw,
    but conservatively compliant -- used to leave the display red after the
    detector's own episode had already closed. ``_estimate`` fixes
    ``speed_stddev_mps`` at 0.04; with the manifest's ``confidence_sigma`` of
    2.0 that is an 0.08 m/s margin, so 0.85 m/s against a 0.8 limit is
    raw-over-limit (0.85 > 0.8) but conservatively compliant (0.85-0.08=0.77).
    """

    node._on_estimate(_estimate(station_m=10.0, speed_mps=1.02, limit_mps=0.8))
    violation = SpeedViolation()
    violation.event_id = 1
    violation.exceedance_mps = 0.22
    node._on_violation(violation)
    assert _published(node)["readout"][0].color.r > 0.8  # violating red

    node._on_estimate(_estimate(station_m=12.0, speed_mps=0.85, limit_mps=0.8))
    readout = _published(node)["readout"][0]
    assert readout.color.g > 0.5, "a conservatively compliant measurement must clear the display"
    # The printed margin must use the same conservative speed as the rearm
    # decision above: 0.85 - 2.0*0.04 = 0.77, an 0.8-0.77 = +0.03 m/s margin.
    # A margin computed from the raw speed instead would print a negative
    # number here (0.8-0.85 = -0.05) under a "compliant" label -- the exact
    # self-contradiction A6-M2's display half left open.
    assert "compliant   +0.03 m/s margin" in readout.text
    assert "-0.05" not in readout.text


def test_scene_is_drawn_before_any_estimate_arrives(node, manifest: Path) -> None:
    """An interviewer opening RViz early must still see the corridor and P."""

    namespaces = _published(node)
    assert {"corridor", "occluders", "route", "fiducials", "actors"} <= set(namespaces)
    assert "waiting" in namespaces["readout"][0].text

    block = json.loads(manifest.read_text(encoding="utf-8"))["profiles"]["nominal_m6_n3"]
    low = block["police_bounds_min_xyz_m"]
    high = block["police_bounds_max_xyz_m"]
    police = namespaces["actors"][0]
    assert police.pose.position.x == pytest.approx((low[0] + high[0]) / 2.0)
    assert police.pose.position.y == pytest.approx((low[1] + high[1]) / 2.0)

    # Every wall in the scene must be drawn, not just the ones the occlusion
    # proof reasons about. Drawing only the occluder list left the east-wall
    # stub invisible while A drove around it (ADR 0018). The count comes from
    # the manifest so a newly authored wall cannot go unrendered.
    assert len(namespaces["occluders"]) == len(block["walls"])
    assert set(block["walls"]) >= {name.rsplit("/", 1)[-1] for slab in block["occluders"]
                                   for name in [slab["prim_path"]]}, (
        "every occluder must also be a wall; they are the same surfaces"
    )
    assert "EastWallStub" in block["walls"], "the stub is a wall and must be published"
