"""A material CameraInfo change must reset the observer's observation window.

Differencing a station computed under one pixel model against one computed
under a different model would silently mix the two into one speed estimate.
The sensor contract has always said a changed K, D, dimensions,
distortion-model, or frame resets the estimator, but nothing in the node
detected that change (A6-M3). These tests drive the real ROS adapter with
synthetic frames, the same way the live and synthetic demonstrations do.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import rclpy
from rclpy.time import Time
from scene.build import build_scene
from sensor_msgs.msg import CameraInfo, Image

# corridor_interfaces is generated by colcon, so it exists under `colcon test`
# but not in a bare repository pytest run. node.py imports it at module level.
pytest.importorskip(
    "corridor_interfaces.msg", reason="colcon-generated interfaces; run via colcon test"
)

from police_observer.node import PoliceObserverNode  # noqa: E402
from police_observer.synthetic import SyntheticCamera  # noqa: E402


@pytest.fixture(scope="module")
def manifest(tmp_path_factory: pytest.TempPathFactory) -> Path:
    output = tmp_path_factory.mktemp("calibration_reset") / "corridor.usda"
    _, manifest_path = build_scene(None, output, 6.0, 3.0)
    return manifest_path


@pytest.fixture()
def node(manifest: Path):
    rclpy.init(args=["--ros-args", "-p", f"manifest_path:={manifest}"])
    observer = PoliceObserverNode()
    try:
        yield observer
    finally:
        observer.destroy_node()
        rclpy.shutdown()


def _frame(camera: SyntheticCamera, station_m: float, timestamp_s: float, distortion_model: str):
    calibration = camera.calibration
    pixels = camera.render(station_m)
    stamp = Time(nanoseconds=round(timestamp_s * 1e9)).to_msg()

    image = Image()
    image.header.stamp = stamp
    image.header.frame_id = calibration.frame_id
    image.height = calibration.height
    image.width = calibration.width
    image.encoding = "bgr8"
    image.is_bigendian = False
    image.step = calibration.width * 3
    image.data = pixels.tobytes()

    info = CameraInfo()
    info.header = image.header
    info.height = calibration.height
    info.width = calibration.width
    info.distortion_model = distortion_model
    info.d = calibration.distortion.tolist()
    info.k = calibration.matrix.reshape(-1).tolist()
    return image, info


def test_a_distortion_model_change_resets_the_observation_window(node, manifest: Path) -> None:
    """K and D stay numerically identical; only the distortion-model label changes.

    Isolates the reset from the accuracy of any one PnP solve: the two frames
    project identically, so if the window were not reset the second pair would
    simply produce a normal speed measurement instead of starting fresh.
    """

    camera = SyntheticCamera(manifest)

    image1, info1 = _frame(camera, station_m=2.0, timestamp_s=1.0, distortion_model="plumb_bob")
    node._on_frame(image1, info1)
    assert node.pipeline.speed_estimator.observation_count == 1
    assert node.pipeline.speed_estimator.previous is not None
    first_station = node.pipeline.speed_estimator.previous.station_m

    image2, info2 = _frame(camera, station_m=2.8, timestamp_s=1.5, distortion_model="plumb_bob")
    node._on_frame(image2, info2)
    assert node.pipeline.speed_estimator.observation_count == 2, "same model: window accumulates"

    # Same numeric K/D, only the distortion-model label differs -- a change
    # calibration_materially_changed must still catch.
    image3, info3 = _frame(
        camera, station_m=3.6, timestamp_s=2.0, distortion_model="rational_polynomial"
    )
    node._on_frame(image3, info3)
    assert node.pipeline.speed_estimator.observation_count == 1, (
        "a changed distortion model must reset the window before this frame is counted"
    )
    assert node.pipeline.speed_estimator.previous is not None
    assert node.pipeline.speed_estimator.previous.station_m != first_station


def test_a_timestamp_only_change_does_not_reset(node, manifest: Path) -> None:
    """Calibration carries no timestamp, so advancing time alone must not reset."""

    camera = SyntheticCamera(manifest)

    image1, info1 = _frame(camera, station_m=2.0, timestamp_s=1.0, distortion_model="plumb_bob")
    node._on_frame(image1, info1)
    assert node.pipeline.speed_estimator.observation_count == 1

    image2, info2 = _frame(camera, station_m=2.8, timestamp_s=1.5, distortion_model="plumb_bob")
    node._on_frame(image2, info2)
    assert node.pipeline.speed_estimator.observation_count == 2
