#!/usr/bin/env python3
"""Derive a robot-scale corridor config from the authored one.

    python3 tools/scale_scenario.py --factor 0.2 --out config/corridor-robot-scale.yaml

WHY THIS EXISTS
---------------
`docs/ROBO_TASK.pdf` labels the corridor widths only as the symbols m and n and
carries no scale bar. Every metric length in `corridor.yaml` is therefore an
explicit demo choice, never a surveyed value -- the scenario source fixes the
TOPOLOGY, not the dimensions.

Those demo choices were made before a robot existed. They give a 12 m corridor,
6 m wide at the entry, for a robot 0.20 m long and 0.16 m wide. That is a
corridor about 37 times the robot's width, and it is the direct cause of the
degeneracy measured in docs/degeneracy-study.md: the walls sit 3 m away, the end
wall 11.5 m away, and robot1's MS200 cannot range it at all until the robot is
3.5 m in. A scan matcher given nothing but two distant parallel walls has
nothing to lock onto along the corridor axis.

Scaling the WORLD toward the robot fixes that at the source, and it is faithful
to the drawing in a way that picking new arbitrary widths would not be: every
length moves by one factor, so every ratio in the scenario -- and therefore
every geometric argument built on it -- is preserved exactly.

WHAT SCALES AND WHAT DOES NOT
-----------------------------
Scaled: every length. Keys ending in `_m`, which the scenario uses consistently
for metres, plus the width thresholds of the speed policy, which are keyed to
corridor width and would otherwise stop meaning anything.

NOT scaled, deliberately:
  * `_deg`, `_px`, `_hz`, counts, fractions, ids -- not lengths.
  * `limit_mps`. Speeds are a POLICY choice, not a dimension. ADR 0023 pins the
    width->limit table only after a measured profile run, and that table is
    still `[to pin after first profile run]`. Scaling the speeds here would be
    inventing a policy; the widths move and the limits stay, which is visible
    and wrong in the right direction -- it makes the un-pinned policy obviously
    un-pinned rather than plausibly wrong.
  * The ROBOT. It is a real 0.20 x 0.16 m machine, and nav2's `robot_radius`
    describes it, not the world. The whole point is that the world shrinks
    toward a fixed robot.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

#: Keys whose values are lengths in metres. `_m` is the scenario's own
#: convention; the two explicit entries are lengths that do not carry the
#: suffix.
LENGTH_SUFFIX = "_m"
EXPLICIT_LENGTH_KEYS = {"maximum_width_m"}

#: Keys that end in `_m` by coincidence of another unit, or that are lengths
#: this tool must not touch.
NOT_LENGTHS = {"limit_mps"}


def is_length_key(key: str) -> bool:
    if key in NOT_LENGTHS:
        return False
    if key in EXPLICIT_LENGTH_KEYS:
        return True
    return key.endswith(LENGTH_SUFFIX) and not key.endswith("_mps")


def scale_node(node: object, factor: float, key: str | None = None) -> object:
    """Recursively scale every length, leaving everything else untouched."""

    if isinstance(node, dict):
        return {name: scale_node(value, factor, name) for name, value in node.items()}
    if isinstance(node, list):
        return [scale_node(item, factor, key) for item in node]
    if isinstance(node, bool) or node is None:
        return node
    if isinstance(node, (int, float)) and key is not None and is_length_key(key):
        return round(float(node) * factor, 6)
    return node


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", default="src/corridor_scene/config/corridor.yaml")
    parser.add_argument("--factor", type=float, required=True)
    parser.add_argument("--out", required=True)
    arguments = parser.parse_args()

    if not 0.0 < arguments.factor <= 1.0:
        raise SystemExit("--factor must be in (0, 1]")

    source = Path(arguments.config)
    document = yaml.safe_load(source.read_text(encoding="utf-8"))
    scaled = scale_node(document, arguments.factor)

    header = (
        f"# DERIVED FILE -- do not hand-edit.\n"
        f"# Generated by tools/scale_scenario.py --factor {arguments.factor}\n"
        f"# from {source.as_posix()}.\n"
        f"#\n"
        f"# Every length is multiplied by {arguments.factor}; every ratio in the\n"
        f"# scenario is therefore unchanged, and so is every geometric argument\n"
        f"# built on it. The supplied drawing has no scale bar, so the authored\n"
        f"# metres were always demo choices -- this simply chooses them for a\n"
        f"# 0.20 x 0.16 m robot instead of for nothing in particular.\n"
        f"#\n"
        f"# NOT scaled: limit_mps (a policy, still un-pinned per ADR 0023),\n"
        f"# angles, pixels, rates, counts, and the robot itself.\n"
    )
    destination = Path(arguments.out)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        header + yaml.safe_dump(scaled, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )

    geometry = scaled["geometry"]
    print(f"scaled by {arguments.factor} -> {destination}")
    print(f"  corridor length {geometry['corridor_length_m']} m")
    for name, entry in geometry["profiles"].items():
        print(f"  {name:22} entry {entry['entry_width_m']} m  corner {entry['corner_width_m']} m")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
